### ISSUE TITLE
Delete empty todo items without confirmation

### ISSUE THREAD

**Issue by jane-lan** [Gimanh/handscream#1]
This message is very tiring. Just delete item without comment end other data.

<img width="573" alt="Screenshot 2020-05-14 at 19 47 32" src="https://user-images.githubusercontent.com/65359156/81962216-198ad100-961c-11ea-92c3-0d747c403b27.png">

**Comment by Gimanh** [comment]
Thanks! You are right. Will be fixed in next version.

**Comment by Gimanh** [comment]
Fixed in https://github.com/Gimanh/handscream/releases/tag/v1.2.4 
Now if empty item does not have reminder or notes, it will be deleted silently.
