### ISSUE TITLE
Bug with storage

### ISSUE THREAD

**Issue by jane-lan** [Gimanh/handscream#3]
**Steps to reproduce**
1. Create/open database
2. Add goal 
3 Add item to goal 
4. Add todo item
5. Then select "Create storage"
6. Enter name and "Accept"

I expect clearing work space, but I see data from old storage

**Comment by Gimanh** [comment]
Thanks! Will be fixed in next version.

**Comment by Gimanh** [comment]
Fixed in https://github.com/Gimanh/handscream/releases/tag/v1.2.4
