### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Jisco** [Gimanh/handscream#6]
Hello,
I just wanted to report a little bug... 😁 

No texts were translated when the app was started for the first time. Everywhere only the key values that starts with "msg.".
After manually changing the translation to English, everything seems to work except the report section:

![image](https://user-images.githubusercontent.com/770001/89031588-122db680-d333-11ea-9632-853a919e2ad5.png)

**Comment by Gimanh** [comment]
Hi!
Thanks for bug report! 

But I can not reproduce this bug.

Can you help me and write steps for reproduction?
Which version do you use? I have tested with 1.11.0

**Comment by Jisco** [comment]
Hi,
sorry for the little delay.
So I also took version 1.11.0. However, I changed the installation directory and did not install it on my standard drive. Maybe you can reproduce it like this.

Or you have to delete the settings folder "C: \Users\{USER}\AppData\Roaming\taskview". ^^

**Comment by Gimanh** [comment]
> Hi,
> 
> sorry for the little delay.
> 
> So I also took version 1.11.0. However, I changed the installation directory and did not install it on my standard drive. Maybe you can reproduce it like this.
> 
> 
> 
> Or you have to delete the settings folder "C: \Users\\{USER}\AppData\Roaming\taskview". ❓ 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/770001/89147372-b6dc0e00-d556-11ea-9cef-52ab531cbcdb.png)
> 
> 

Thanks!
Can you tel me what is default language  in your operation system? 
When I tried reproduce, I start installation from version 1.5.  :(
Thank you for help! 
I will test it today!

**Comment by Jisco** [comment]
Hi,
i'm using Windows 10 with german as default language.

**Comment by Gimanh** [comment]
> I'm using Windows 10 with german as default language.

Hi! Thank you so much for your help!
I have already find and fixed this bug. 
I had no analyse undefined languages. 
In next release will work correctly.
Can you help me translate locales to German?

**Comment by Jisco** [comment]
I would like to do that. Just tell me how we go about it. 😄 

Do you speak Russian otherwise? Would be great if you could also translate my [app](https://github.com/Jisco/VisualFamilyTree/blob/master/Languages/ReadMe.md) too. 😀

**Comment by Gimanh** [comment]
> Sure, I would like to do that. Just tell me how we go about it. 🆗 😎
> 
> Do you speak Russian otherwise? Would be great if you could also translate my [app](https://github.com/Jisco/VisualFamilyTree/blob/master/Languages/ReadMe.md) too. 😀

Sure, I will make PR with Russian locales for you app. 
For my app I will add folder with locales and then you will be able created PR with German :)
On this week I will make build/release for all platforms with bug fixes.

**Comment by Gimanh** [comment]
> Sure, I would like to do that. Just tell me how we go about it. 🆗 😎
> 
> Do you speak Russian otherwise? Would be great if you could also translate my [app](https://github.com/Jisco/VisualFamilyTree/blob/master/Languages/ReadMe.md) too. 😀

Hi!
I added languages https://github.com/Gimanh/handscream/tree/master/Languages
Thanks you for help!

**Comment by Gimanh** [comment]
Fixed in release https://github.com/Gimanh/handscream/releases/tag/v1.12.2
