### ISSUE TITLE
Fixed Window Height

### ISSUE THREAD

**Issue by mansoorahmedmemon** [Gimanh/handscream#8]
Can you please add a maximize button to the main panel.

The height of window is fixed and causes alot of issues with this app.
Especially when opening dialog boxes.

I am using Ubuntu 20.04.

**Comment by Gimanh** [comment]
> Can you please add a maximize button to the main panel.
> 
> The height of window is fixed and causes alot of issues with this app.
> Especially when opening dialog boxes.
> 
> I am using Ubuntu 20.04.

Hi which panel do you need to add a maximize button to? 
I did not quite understand what kind of panel we are talking about.

**Comment by mansoorahmedmemon** [comment]
The main panel.

For me its stuck at the center of the screen with a fixed height. Although the width can be adjusted.

Monitor Resolution: 1366x768

**Comment by Gimanh** [comment]
> The main panel.
> 
> For me its stuck at the center of the screen with a fixed height. Although the width can be adjusted.
> 
> Monitor Resolution: 1366x768
<img width="1357" alt="ubuntu_max" src="https://user-images.githubusercontent.com/10837815/96920558-fc550b00-14b5-11eb-8e79-aeb7dcc4e504.png">

If I understand correctly, you are talking about the red highlight in the screenshot. Is it?

**Comment by mansoorahmedmemon** [comment]
No, its the close button.

I am talking about the `maximize` button, as highlighted in the windows screenshot (the black one).
Its not showing up for the Linux version.

**Comment by Gimanh** [comment]
> No, its the close button.
> 
> 
> 
> I am talking about the `maximize` button, as highlighted in the windows screenshot (the black one).
> 
> Its not showing up for the Linux version.

I will fix it in the next version. Thank you for help!

**Comment by mansoorahmedmemon** [comment]
Thanks Bro!
